name: Build AC1200HP_K2

on: 
  workflow_dispatch:
    inputs:
      uploadwet:
        type: boolean
        description: 'whether to upload firmware to wettransfer'
        default: 'true'
env:
  TIME_ZONE: Asia/Shanghai
  FIRMWARE_PATH: /opt/firmwares
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/git-core-ubuntu-ppa-xenial.list
        sudo add-apt-repository ppa:git-core/ppa
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install libncurses5 libncurses5-dev m4 bison gawk flex libstdc++-4.8-dev g++-multilib g++ \
        gengetopt git gitk zlib1g-dev autoconf autopoint libtool shtool autogen mtd-utils intltool sharutils \
        docbook-xsl-* libstdc++5 texinfo dos2unix xsltproc binutils u-boot-tools device-tree-compiler python \
        qemu gperf liblzo2-dev uuid-dev build-essential lzma-dev liblzma-dev lzma patch cmake intltool yodl yodl-doc \
        libglib2.0-dev gtk-doc-tools libc6-i386 lib32stdc++6 lib32z1 libelf1:i386 lib32ncurses5 libc6-dev-i386 libstdc++6:i386
        sudo timedatectl set-timezone "$TIME_ZONE"
    - name: Clone source code
      run: |
        git clone https://github.com/KevinandJacky/RT-AC1200HP_3.0.0.4.380.8287-for-K2.git /opt/asus
    - name: Apply patches
      run: |
        cp -f Custom/patches/init.c /opt/asus/release/src/router/rc/init.c
        cp -f Custom/patches/target.mak /opt/asus/release/src-rt/target.mak
        cp -f Custom/patches/ralink_spi.c /opt/asus/release/src-ra-mt7620/linux/linux-2.6.36.x/drivers/mtd/ralink/ralink_spi.c
        cp -f Custom/patches/ralink_bbu_spi.c /opt/asus/release/src-ra-mt7620/linux/linux-2.6.36.x/drivers/mtd/ralink/ralink_bbu_spi.c
        cp -f Custom/patches/extendno.conf /opt/asus/release/src/router/extendno.conf
        cp -f Custom/patches/CN.dict /opt/asus/release/src/router/www/CN.dict
        cp -f Custom/patches/EN.dict /opt/asus/release/src/router/www/EN.dict
        cp -f Custom/patches/asustitle.png /opt/asus/release/src/router/www/images/New_ui/asustitle.png
    - name: Build firmware
      run: |
        cp -f Custom/build.sh /opt/asus/build.sh
        cd /opt/asus
        sudo chmod +x build.sh
        sudo ./build.sh
    - name: Organize firmware files
      id: organize
      run: |
        mkdir -p $FIRMWARE_PATH/
        cd /opt/asus/release/src-ra-mt7620/image
        for firmwarefile in $(ls RT-AC1200HP_3.0.0.4*.trx)
        do sudo mv -f $firmwarefile $FIRMWARE_PATH/RT_AC1200HP_K2.trx
        done
        cd $FIRMWARE_PATH
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name : Upload packages
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success'
      with:
        name: AC1200HP-packages
        path: ${{ env.FIRMWARE }}
    - name: Upload firmware to WeTransfer
      if: steps.organize.outputs.status == 'success' && github.event.inputs.uploadwet == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
        echo "WETRANSFER_URL=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_ENV
